version: "3.9"

services:
  backend:
    build: backend
    volumes:
      - static_volume:/app/staticfiles
    env_file:
      - .env
    expose:
      - 8000

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - static_volume:/app/staticfiles
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

volumes:
  static_volume:
